import './js/header';
import './js/hero';
import './js/about_me';
import './js/benefits';
import './js/projects';
import './js/faq';
import './js/covers';
import './js/reviews';
import './js/work_tougether';
